name: Docker images of OpenFAST
on:
  push:
    branches: ['main']


jobs:
  build-and-push-image:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: cardinalby/export-env-action@v2
        with:
          envFile: '.env'  

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHREGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKERREGISTRY }}/${{ env.OPENFAST_IMAGE_NAME }}
            ${{ env.GHREGISTRY }}/${{ env.OPENFAST_IMAGE_NAME }}

      # Versioned main image
      - name: Build and push Docker - main release
        if: always()
        uses: docker/build-push-action@v4
        with:
          context: ./openfast
          file: ./openfast/Dockerfile-main
          push: true
          build-args: |
            OPENFAST_MAIN=${{ env.OPENFAST_MAIN }}
          tags: |
            ${{ env.DOCKERREGISTRY }}/${{ env.OPENFAST_IMAGE_NAME }}:${{ env.OPENFAST_MAIN }}
            ${{ env.DOCKERREGISTRY }}/${{ env.OPENFAST_IMAGE_NAME }}:latest
            ${{ env.GHREGISTRY }}/${{ env.OPENFAST_IMAGE_NAME }}:${{ env.OPENFAST_MAIN }}
            ${{ env.GHREGISTRY }}/${{ env.OPENFAST_IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      # Dev image
      - name: Build and push Docker - Dev
        if: always()
        uses: docker/build-push-action@v4
        with:
          context: ./openfast
          file: ./openfast/Dockerfile-dev
          push: true
          build-args: |
            OPENFAST_MAIN=${{ env.OPENFAST_DEV }}
          tags: |
            ${{ env.DOCKERREGISTRY }}/${{ env.OPENFAST_IMAGE_NAME }}:${{ env.OPENFAST_DEV }}
            ${{ env.GHREGISTRY }}/${{ env.OPENFAST_IMAGE_NAME }}:${{ env.OPENFAST_DEV }}
          labels: ${{ steps.meta.outputs.labels }}